image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

platform:
  - x64
  - x86

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node -e "console.log(`${process.version} ${process.arch} ${process.platform}`)"
  - npm --version
  - npm test

build: off
